server:
  port: 6868

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-instance-hackathon-7up.c3rewq8fyion.ap-northeast-1.rds.amazonaws.com:3306/CPM
    username: admin
    password: tcbs1234
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  url:
    wso2is:
      base: https://wso2is-sit.tcbs.com.vn
      scim2: ${spring.url.wso2is}/scim2
      get-user-info: ${spring.url.wso2is.base}/Users?filter=userName+Eq+
      get-group-info: ${spring.url.wso2is.base}/Groups?filter=displayName+Eq+
      token: "Basic YWRtaW46YWRtaW4="